{
    'name': 'Componedor de Paquetes',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Componedor de Paquetes automatico basado en reglas de despacho',
    'description': """ Componedor de Paquetes automatico basado en reglas de despacho para envio con transportistas   """,
    'license': '',
    'author': 'Lazaro O Farril, Yadier Quesada, Jose Ribe ,Grupo Espiral',
    "depends" : ['base','contacts','stock','sale','website', 'report_xml', 'report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        #'security/security.xml',
        'views/actions_views.xml',
        'views/menu_items.xml',
        'views/inherit_views.xml',
        'views/envoy_views.xml',
        'views/package_views.xml',
        'views/portal_sale_template.xml',
        'data/sequences.xml',
        #reportes
        'report/report_menu.xml',
        'report/report_manifest_template.xml',
        'report/report_hbl_template.xml',
        'report/report_container_hbl_template.xml',
        'report/report_cdfi_invoice_template.xml',
        'report/report_packing_list_template.xml',
        'report/sale_order_report.xml',
        'report/report_tag_template.xml',
        'report/report_envoy_tag_template.xml',
        #templates
        'report/Manifiesto_template_xml.xml',
        'report/CDFI_template_xml.xml',
        #data
        'data/productos.xml',
        'demo/report.xml',
    ],
    'installable': True,
    'application': True,
}
